### ISSUE TITLE
Running run-rs -v 4.0.2 starts downloading mongodb

### ISSUE THREAD

**Issue by chaiwa-berian** [vkarpov15/run-rs#10]
I am finding it odd for `run-rs` to start downloading mongodb even when mongodb is already installed! Why does it have to download the same thing again when it already exists? The documentation for running `run-rs` indicates that I can run it with a different version, other than the default mongodb version, by executing the `run-rs -v 4.0.2` command, but that is not the case! I am made to go through the whole download process!

Can I use the already installed version of mongodb which supports multi-document transactions without `run-rs` downloading the whole thing again? This would mean having so many instances of mongodb on my machine which may end-up into unforeseen disaster. Am I missing something?

**Comment by vkarpov15** [comment]
We added a `--mongod` version in 0.2.1 to work around this. Run-rs downloads MongoDB so you don't have to worry about doing it yourself, having to re-install mongodb everywhere when you have to manage multiple versions and different machines is very annoying. We added a note in the readme about this option: https://github.com/vkarpov15/run-rs#reusing-a-pre-installed-mongodb-version
