### ISSUE TITLE
bind to different interface

### ISSUE THREAD

**Issue by Christilut** [vkarpov15/run-rs#17]
Run-rs binds to localhost by default, but I need it to listen on a different interface. Is that possible?

**Comment by chaiwa-berian** [comment]
@christilut if you are Windows it should be able to bind to whatever the hostname of your machine is. On linux/mac it should bind to localhost or 127.0.0.1!

What is your development environment like?

**Comment by chaiwa-berian** [comment]
@christilut did you mean if `run-rs` supports running it with a `--host` option so it can be bound to any host where the replica set is running?

**Comment by Christilut** [comment]
I'm on Linux (ubuntu 18.04). Yea I mean a host option. In the normal MongoDB installation I would have to use `bindIp` and set it to my local network interface.

**Comment by chaiwa-berian** [comment]
> I'm on Linux (ubuntu 16.04). Yea I mean a host option. In the normal MongoDB installation I would have to use `bindIp` and set it to my local network interface.
> 
> I'm using it on a Lightsail VPS and localhost isn't exposed to the outside network there and I have to bind mongo to the private network IP address that AWS gives me.

Ok that sounds fair! Looking at the current codebase, the `--host` is not supported but I will make a pull request for it shortly so we can check it out!

**Comment by Christilut** [comment]
Awesome!

**Comment by chaiwa-berian** [comment]
@Christilut See this pull request #18

**Comment by Christilut** [comment]
Thanks, works perfectly.

I am wondering now how to enable authentication for run-rs, I think that's also not yet implemented? Maybe a simple flag `--enableAuthentication` that would change the mongo config to:
```
security:
    authorization: "enabled"
```

I'm running a development server, so it's not a huge deal. 
Maybe it makes sense to parse a config file similar to `mongod.conf` with all the settings?

**Comment by chaiwa-berian** [comment]
@Christilut Good to know it works! We wait @vkarpov15 's approval to merge the pull request

**Comment by chaiwa-berian** [comment]
> Thanks, works perfectly.
> 
> I am wondering now how to enable authentication for run-rs, I think that's also not yet implemented? Maybe a simple flag `--enableAuthentication` that would change the mongo config to:
> 
> ```
> security:
>     authorization: "enabled"
> ```
> I'm running a development server, so it's not a huge deal.
> Maybe it makes sense to parse a config file similar to `mongod.conf` with all the settings?

Great idea, kindly open a new issue for that! :)

**Comment by vkarpov15** [comment]
Auth is something we will consider for the future but it isn't a big concern. Run-rs should only be used for local dev, so auth isn't a major concern

**Comment by Christilut** [comment]
Totally agree. I'm using run-rs now on a VPS because Atlas has a bug where the free tier can't support transactions. I guess I'll do some ip whitelisting for now.
