### ISSUE TITLE
Unable to "npm i -g run-rs"

### ISSUE THREAD

**Issue by YashGadle** [vkarpov15/run-rs#22]
npm ERR! path /usr/local/lib/node_modules/run-rs/node_modules/detect-libc/bin/detect-libc.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/run-rs/node_modules/detect-libc/bin/detect-libc.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

**Comment by vkarpov15** [comment]
Which version of npm and what's your OS? Also, maybe just try again? I've had a couple similar instances with npm and other packages, they've proven to be intermittent issues.
