### ISSUE TITLE
Using --keep flag fails on first run

### ISSUE THREAD

**Issue by iansu** [vkarpov15/run-rs#3]
If I include the `--keep` flag on the first run I get an error and mongo won't start. I'd like to just have something like this in my `package.json` and be able to use the same command on the first run and any subsequent runs:

```
"start:mongo": "run-rs -v 4.0.1 --keep"
```

**Comment by vkarpov15** [comment]
Thanks for reporting, just released 0.1.3 with a fix :+1:

**Comment by iansu** [comment]
Thanks for the quick fix! This package is great. It saved me the trouble of getting this working with docker-compose.

**Comment by vkarpov15** [comment]
Glad you found it useful! Yeah docker-compose is a major headache in my experience.

**Comment by iansu** [comment]
This seems to have created another issue when running with `--keep` on the first run. The problem is somewhere around here: https://github.com/vkarpov15/run-rs/blob/master/index.js#L64

Since it hasn't been run before it should be doing `rs.start()` but because of the `--keep` flag it's trying to restart a replica set that doesn't actually exist yet.

**Comment by iansu** [comment]
I'm happy to submit a PR if you don't have time to fix this right now. Let me know.

**Comment by vkarpov15** [comment]
Just released 0.1.4 with a fix :+1:

**Comment by iansu** [comment]
I just tested it and can confirm that it works. Thanks again!

**Comment by iansu** [comment]
It's for work so I can't really give a lot of details. Our app requires transactions so we need to use MongoDB 4. In order to use transactions you must have a replica set, even when running locally. We were previously using docker to run mongo locally. It ended up being a pain to get a replica set running properly with docker-compose so I decided to give this a try instead. So far the experience has been much better and easier to get running.

**Comment by vkarpov15** [comment]
Thanks for the info, don't hesitate to reach out if you have any problems or suggestions for improvements.
