### ISSUE TITLE
How to disable console output

### ISSUE THREAD

**Issue by lahiruchandima** [vkarpov15/run-rs#34]
Is there any way to disable console output from run-rs command? When I do a mongorestore for a dataset about 500MB on the replica set, it takes a long time for the console output to finish.

**Comment by lahiruchandima** [comment]
Another problem, when I use --keep option, run-rs gives a very large console output when there is data in the db, which takes several minutes to complete. Any way to prevent this?

**Comment by mexin** [comment]
@lahiruchandima you could try running with `--shell` option I was having the same problems with the console output and that option solved it for me, hope it helps.

**Comment by baldercm** [comment]
@lahiruchandima @mexin I just saw there is also a `--quiet` option that will suppress oplog tailing without starting the shell.

**Comment by vkarpov15** [comment]
The `--quiet` option is the way to go
