### ISSUE TITLE
Merge pending PR #32

### ISSUE THREAD

**Issue by baldercm** [vkarpov15/run-rs#36]
Hi, and thanks for this great module, it's being really helpful :)

I just tried using the `--help` option, but it does not work (version `0.5.2`, latest available on npm). I was going to submit a PR to fix it, and then realized it was already fixed on #32 

It would be great if you can release a new version including this fix.

**Comment by vkarpov15** [comment]
I just released 0.5.3, sorry for the inconvenience and thanks for reporting this issue :+1:
