### ISSUE TITLE
bind_ip_all - Usage for local dev + docker.

### ISSUE THREAD

**Issue by j** [vkarpov15/run-rs#42]
Can I allow connections from any host/ip?  I'm unable to get `--host` option to work with docker.

**Comment by vitorsilvalima** [comment]
I have created a dockerfile to run it 

https://github.com/vitorsilvalima/mongodb-replica-set-docker

what do you think about it?

**Comment by buccfer** [comment]
What's the status of this? Can we add the bind_ip_all flag?
