### ISSUE TITLE
What the hell.....

### ISSUE THREAD

**Issue by ankurloriya** [vkarpov15/run-rs#44]
I hitted this command and `~/data` directory cleaned...
This very rediculus thing in this command. at least you need to ask command will use your dirctory and do you want to remove it.
There are no any notification about deleting directory....

F__k....

Please fix this otherwise other people can suffer same problem.

**Comment by vkarpov15** [comment]
It's the first section on the readme: https://github.com/vkarpov15/run-rs#clearing-the-database .

**Comment by ankurloriya** [comment]
Best way is application --clean-dir would be perfect thing to accident lost of data.


> It's the first section on the readme: https://github.com/vkarpov15/run-rs#clearing-the-database .

@vkarpov15 I think default should --keep .

Actually I lost my documents, server pem which was in ~/data/
Generally should aware before clean if application found strange data. in ~/data/ or ask "do you want clean directroy (~/data) to start application?" 

Actully did worng thing in application code.
