### ISSUE TITLE
Can't connect with --bind_ip_all flag

### ISSUE THREAD

**Issue by janantala** [vkarpov15/run-rs#50]
Hello there,

I am ussing `mongodb` hostname in docker container with `MONGODB_URL=mongodb://mongodb:27017,mongodb:27018,mongodb:27019/test?replicaSet=rs` connection string for tests, but I can't connect to it after 0.7.0 run-rs release.

I use the command to run docker image:
```
CMD ["run-rs", "--host", "mongodb", "--mongod"]
```
It works fine when I use `RUN npm install run-rs@0.6.2 --unsafe-perm -g`
How should I connect to it?

**Comment by vkarpov15** [comment]
Fix should be in v0.7.1 :+1:
