### ISSUE TITLE
Is it possible to configure the ports?

### ISSUE THREAD

**Issue by chinnichaitanya** [vkarpov15/run-rs#58]
Currently I think the replica set is running on ports 27017, 27018 and 27019. Is it possible to configure these to run on different ports using some flag? 

I require this for my local setup since I already have a MongoDB server running for a different project and do not want to stop it every time.

PS: I do not want to use the existing mongo since both are different projects.

**Comment by hi-usui** [comment]
Yes, were you able to find it? it seems you can supply CLI option "--portStart"

https://github.com/vkarpov15/run-rs/blob/1a217d028352c84f41eda7928597d2f89fda1d31/src/options.js

**Comment by chinnichaitanya** [comment]
Thank you so much @hi-usui.
@vkarpov15 I feel it could be updated in README for better identification.

Closing this for now!
