### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by stherrienaspnet** [vkarpov15/run-rs#9]
Hello, is it possible to run a replicat set compose of a single mongodb server?

Thanks

**Comment by stherrienaspnet** [comment]
Thanks for the quick reply, could you point me where could i make temporary change for it if this is quick like removing the 2 other server instances?

**Comment by stherrienaspnet** [comment]
Thanks you very much for your changes! Unfortunately, i just read on mongodb site that when your specify only one server instance into the connection string using the replicat set option mongo is creating a standalone server connection. Here is what i have done:
1- stopped my mongodb service that is running when my laptop is booting
2- start the service like this -> mongod --replSet rs0
3-   const dbClient: MongoClient = await  MongoClient.connect('mongodb://localhost:27017/rollback-test/?replicaSet=rs0', {useNewUrlParser: true});
Here is the result: UnhandledPromiseRejectionWarning: MongoError: no primary found in replicaset or invalid replica set name.

Here is what I have read from Mongo Web site, maybe I have a bad understanding, could you confirm me if you also see having replicat set on a single instance make transaction NOT AVAILAIBLE.

Mongo doc:

replicaSet | Specifies the name of the replica set, if the mongod is a member of a replica set.When connecting to a replica set it is important to give a seed list of at least two mongodinstances. If you only provide the connection point of a single mongod instance, and omit the replicaSet, the client will create a standalone connection.
-- | --
Thanks for your time :)

**Comment by vkarpov15** [comment]
If you specify the replicaSet option in your query string, the MongoDB driver will try to make a replica set connection, even if you only have 1 host in your connection string. That error message looks like you're trying to connect to a standalone mongod instance as a replica set, which you can't do. There's a difference between a 1 node replica set and a standalone mongod. Try using `run-rs -n 1` and see if that works.

**Comment by stherrienaspnet** [comment]
Thanks you very much!

Le jeu. 4 oct. 2018 11:16, Valeri Karpov <notifications@github.com> a
écrit :
